version : '2'

services:
  postgres:
    image: 'postgres:last'
    restart: always
    volumes:
      - './${VOLUME_FOLDER}:/var/lib/postgres/data'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${PORT}:${PORT}